============================= test session starts ==============================
platform darwin -- Python 3.9.22, pytest-8.4.0, pluggy-1.6.0
rootdir: /Users/andreanovoa/real-time-bias-aware-DA/PRIVATE_real-time-bias-aware-DA
plugins: anyio-4.9.0
collected 16 items

test_tutorials.py .........FF..FFF                                       [100%]

=================================== FAILURES ===================================
_______________ test_notebook_runs[tutorials/20_Rijke_LOM.ipynb] _______________

notebook_path = 'tutorials/20_Rijke_LOM.ipynb'

    @pytest.mark.parametrize("notebook_path", NOTEBOOKS)
    def test_notebook_runs(notebook_path):
        """Test that a notebook runs without error."""
>       assert run_notebook(notebook_path, timeout=TIMEOUT, quick=QUICK), f"Notebook failed: {notebook_path}"
E       AssertionError: Notebook failed: tutorials/20_Rijke_LOM.ipynb
E       assert False
E        +  where False = run_notebook('tutorials/20_Rijke_LOM.ipynb', timeout=600, quick=False)

test_tutorials.py:71: AssertionError
----------------------------- Captured stdout call -----------------------------
Testing tutorials/20_Rijke_LOM.ipynb...Error executing tutorials/20_Rijke_LOM.ipynb: An error occurred while executing the following cell:
------------------
import matplotlib; matplotlib.use('Agg')  # Disable plotting
from essentials.models_physical import Rijke
case = Rijke()

state, t_ = case.time_integrate(int(case.t_transient / case.dt))
case.update_history(state, t_)

------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[1], line 2[0m
[1;32m      1[0m [38;5;28;01mimport[39;00m[38;5;250m [39m[38;5;21;01mmatplotlib[39;00m; matplotlib[38;5;241m.[39muse([38;5;124m'[39m[38;5;124mAgg[39m[38;5;124m'[39m)  [38;5;66;03m# Disable plotting[39;00m
[0;32m----> 2[0m [38;5;28;01mfrom[39;00m[38;5;250m [39m[38;5;21;01messentials[39;00m[38;5;21;01m.[39;00m[38;5;21;01mmodels_physical[39;00m[38;5;250m [39m[38;5;28;01mimport[39;00m Rijke
[1;32m      3[0m case [38;5;241m=[39m Rijke()
[1;32m      5[0m state, t_ [38;5;241m=[39m case[38;5;241m.[39mtime_integrate([38;5;28mint[39m(case[38;5;241m.[39mt_transient [38;5;241m/[39m case[38;5;241m.[39mdt))

[0;31mModuleNotFoundError[0m: No module named 'essentials'

____________ test_notebook_runs[tutorials/21_TADA_Rijke_twin.ipynb] ____________

notebook_path = 'tutorials/21_TADA_Rijke_twin.ipynb'

    @pytest.mark.parametrize("notebook_path", NOTEBOOKS)
    def test_notebook_runs(notebook_path):
        """Test that a notebook runs without error."""
>       assert run_notebook(notebook_path, timeout=TIMEOUT, quick=QUICK), f"Notebook failed: {notebook_path}"
E       AssertionError: Notebook failed: tutorials/21_TADA_Rijke_twin.ipynb
E       assert False
E        +  where False = run_notebook('tutorials/21_TADA_Rijke_twin.ipynb', timeout=600, quick=False)

test_tutorials.py:71: AssertionError
----------------------------- Captured stdout call -----------------------------
Testing tutorials/21_TADA_Rijke_twin.ipynb...Error executing tutorials/21_TADA_Rijke_twin.ipynb: An error occurred while executing the following cell:
------------------
import matplotlib; matplotlib.use('Agg')  # Disable plotting
from essentials.models_physical import Rijke
from essentials.create import create_truth
from essentials.plotResults import plot_truth

truth = create_truth(model=Rijke,
                     t_start=.2, 
                     t_stop=.6,
                     dt_obs=20,
                    beta=3.2, 
                    tau=1.2e-3)

plot_truth(**truth, f_max=1200, window=0.02, fig_width=12)

------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[1], line 2[0m
[1;32m      1[0m [38;5;28;01mimport[39;00m[38;5;250m [39m[38;5;21;01mmatplotlib[39;00m; matplotlib[38;5;241m.[39muse([38;5;124m'[39m[38;5;124mAgg[39m[38;5;124m'[39m)  [38;5;66;03m# Disable plotting[39;00m
[0;32m----> 2[0m [38;5;28;01mfrom[39;00m[38;5;250m [39m[38;5;21;01messentials[39;00m[38;5;21;01m.[39;00m[38;5;21;01mmodels_physical[39;00m[38;5;250m [39m[38;5;28;01mimport[39;00m Rijke
[1;32m      3[0m [38;5;28;01mfrom[39;00m[38;5;250m [39m[38;5;21;01messentials[39;00m[38;5;21;01m.[39;00m[38;5;21;01mcreate[39;00m[38;5;250m [39m[38;5;28;01mimport[39;00m create_truth
[1;32m      4[0m [38;5;28;01mfrom[39;00m[38;5;250m [39m[38;5;21;01messentials[39;00m[38;5;21;01m.[39;00m[38;5;21;01mplotResults[39;00m[38;5;250m [39m[38;5;28;01mimport[39;00m plot_truth

[0;31mModuleNotFoundError[0m: No module named 'essentials'

___________ test_notebook_runs[tutorials/24_TA_azimuthal_data.ipynb] ___________

notebook_path = 'tutorials/24_TA_azimuthal_data.ipynb'

    @pytest.mark.parametrize("notebook_path", NOTEBOOKS)
    def test_notebook_runs(notebook_path):
        """Test that a notebook runs without error."""
>       assert run_notebook(notebook_path, timeout=TIMEOUT, quick=QUICK), f"Notebook failed: {notebook_path}"
E       AssertionError: Notebook failed: tutorials/24_TA_azimuthal_data.ipynb
E       assert False
E        +  where False = run_notebook('tutorials/24_TA_azimuthal_data.ipynb', timeout=600, quick=False)

test_tutorials.py:71: AssertionError
----------------------------- Captured stdout call -----------------------------
Testing tutorials/24_TA_azimuthal_data.ipynb...Error executing tutorials/24_TA_azimuthal_data.ipynb: An error occurred while executing the following cell:
------------------
import matplotlib; matplotlib.use('Agg')  # Disable plotting
import scipy.io as sio

def fun_PSD(X):
    if X.shape[0] > X.shape[1]:
        X = X.T
    PSD = []
    for x in X:
        yt = np.fft.fft(x)
        PSD.append(2.0 / X.shape[-1] * np.abs(yt[0:X.shape[-1] // 2]))
    return PSD

N, upsample = 1000, 2

fig1 = plt.figure(figsize=(15, 5))
axs = fig1.subplots(2, len(ERs)//2, sharey='all', sharex='all')
for ER, name, ax in zip(ERs, files, axs.ravel()):
    mat = sio.loadmat(name)
    y_raw, t_obs = [mat[key] for key in ['y_raw', 't']]
    y_raw = y_raw[-N::upsample]
    if ER == ERs[0]:
        Nq = y_raw.shape[-1]
        t_obs = t_obs.squeeze()[::upsample]
        dt = t_obs[1]-t_obs[0]
        f = np.linspace(0.0, 1.0 / (2.0 * dt), (N//upsample) // 2)
        colors = plt.cm.afmhot(np.linspace(0,0.7,Nq))[::-1]
        
    psd = fun_PSD(X=y_raw)
    for psd_, c, lw in zip(psd, colors, [3, 2, 1.2, 0.8]):
        ax.plot(f, psd_, color=c, lw=lw)
    ax.set(title='$\Phi={}$'.format(ER))
    
leg = ['$p(\\theta={}^\circ)$'.format(deg) for deg in [0, 60, 120, 240]]
axs[0, -1].legend(leg, loc='upper left', bbox_to_anchor=(1, 1))
[ax.set(xlabel='$f$') for ax in axs[1, :]]
[ax.set(ylabel='PSD', xlim=[100, 3000], ylim=[-10, 600]) for ax in axs[:, 0]];

------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
File [0;32m~/anaconda3/envs/sort/lib/python3.9/site-packages/scipy/io/matlab/_mio.py:39[0m, in [0;36m_open_file[0;34m(file_like, appendmat, mode)[0m
[1;32m     38[0m [38;5;28;01mtry[39;00m:
[0;32m---> 39[0m     [38;5;28;01mreturn[39;00m [38;5;28;43mopen[39;49m[43m([49m[43mfile_like[49m[43m,[49m[43m [49m[43mmode[49m[43m)[49m, [38;5;28;01mTrue[39;00m
[1;32m     40[0m [38;5;28;01mexcept[39;00m [38;5;167;01mOSError[39;00m [38;5;28;01mas[39;00m e:
[1;32m     41[0m     [38;5;66;03m# Probably "not found"[39;00m

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: '/Users/andreanovoa/data/annular/ER_0.4875.mat'

During handling of the above exception, another exception occurred:

[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
Cell [0;32mIn[4], line 18[0m
[1;32m     16[0m axs [38;5;241m=[39m fig1[38;5;241m.[39msubplots([38;5;241m2[39m, [38;5;28mlen[39m(ERs)[38;5;241m/[39m[38;5;241m/[39m[38;5;241m2[39m, sharey[38;5;241m=[39m[38;5;124m'[39m[38;5;124mall[39m[38;5;124m'[39m, sharex[38;5;241m=[39m[38;5;124m'[39m[38;5;124mall[39m[38;5;124m'[39m)
[1;32m     17[0m [38;5;28;01mfor[39;00m ER, name, ax [38;5;129;01min[39;00m [38;5;28mzip[39m(ERs, files, axs[38;5;241m.[39mravel()):
[0;32m---> 18[0m     mat [38;5;241m=[39m [43msio[49m[38;5;241;43m.[39;49m[43mloadmat[49m[43m([49m[43mname[49m[43m)[49m
[1;32m     19[0m     y_raw, t_obs [38;5;241m=[39m [mat[key] [38;5;28;01mfor[39;00m key [38;5;129;01min[39;00m [[38;5;124m'[39m[38;5;124my_raw[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mt[39m[38;5;124m'[39m]]
[1;32m     20[0m     y_raw [38;5;241m=[39m y_raw[[38;5;241m-[39mN::upsample]

File [0;32m~/anaconda3/envs/sort/lib/python3.9/site-packages/scipy/io/matlab/_mio.py:225[0m, in [0;36mloadmat[0;34m(file_name, mdict, appendmat, **kwargs)[0m
[1;32m     88[0m [38;5;250m[39m[38;5;124;03m"""[39;00m
[1;32m     89[0m [38;5;124;03mLoad MATLAB file.[39;00m
[1;32m     90[0m 
[0;32m   (...)[0m
[1;32m    222[0m [38;5;124;03m    3.14159265+3.14159265j])[39;00m
[1;32m    223[0m [38;5;124;03m"""[39;00m
[1;32m    224[0m variable_names [38;5;241m=[39m kwargs[38;5;241m.[39mpop([38;5;124m'[39m[38;5;124mvariable_names[39m[38;5;124m'[39m, [38;5;28;01mNone[39;00m)
[0;32m--> 225[0m [38;5;28;01mwith[39;00m _open_file_context(file_name, appendmat) [38;5;28;01mas[39;00m f:
[1;32m    226[0m     MR, _ [38;5;241m=[39m mat_reader_factory(f, [38;5;241m*[39m[38;5;241m*[39mkwargs)
[1;32m    227[0m     matfile_dict [38;5;241m=[39m MR[38;5;241m.[39mget_variables(variable_names)

File [0;32m~/anaconda3/envs/sort/lib/python3.9/contextlib.py:119[0m, in [0;36m_GeneratorContextManager.__enter__[0;34m(self)[0m
[1;32m    117[0m [38;5;28;01mdel[39;00m [38;5;28mself[39m[38;5;241m.[39margs, [38;5;28mself[39m[38;5;241m.[39mkwds, [38;5;28mself[39m[38;5;241m.[39mfunc
[1;32m    118[0m [38;5;28;01mtry[39;00m:
[0;32m--> 119[0m     [38;5;28;01mreturn[39;00m [38;5;28;43mnext[39;49m[43m([49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mgen[49m[43m)[49m
[1;32m    120[0m [38;5;28;01mexcept[39;00m [38;5;167;01mStopIteration[39;00m:
[1;32m    121[0m     [38;5;28;01mraise[39;00m [38;5;167;01mRuntimeError[39;00m([38;5;124m"[39m[38;5;124mgenerator didn[39m[38;5;124m'[39m[38;5;124mt yield[39m[38;5;124m"[39m) [38;5;28;01mfrom[39;00m[38;5;250m [39m[38;5;28;01mNone[39;00m

File [0;32m~/anaconda3/envs/sort/lib/python3.9/site-packages/scipy/io/matlab/_mio.py:17[0m, in [0;36m_open_file_context[0;34m(file_like, appendmat, mode)[0m
[1;32m     15[0m [38;5;129m@contextmanager[39m
[1;32m     16[0m [38;5;28;01mdef[39;00m[38;5;250m [39m[38;5;21m_open_file_context[39m(file_like, appendmat, mode[38;5;241m=[39m[38;5;124m'[39m[38;5;124mrb[39m[38;5;124m'[39m):
[0;32m---> 17[0m     f, opened [38;5;241m=[39m [43m_open_file[49m[43m([49m[43mfile_like[49m[43m,[49m[43m [49m[43mappendmat[49m[43m,[49m[43m [49m[43mmode[49m[43m)[49m
[1;32m     18[0m     [38;5;28;01mtry[39;00m:
[1;32m     19[0m         [38;5;28;01myield[39;00m f

File [0;32m~/anaconda3/envs/sort/lib/python3.9/site-packages/scipy/io/matlab/_mio.py:45[0m, in [0;36m_open_file[0;34m(file_like, appendmat, mode)[0m
[1;32m     43[0m     [38;5;28;01mif[39;00m appendmat [38;5;129;01mand[39;00m [38;5;129;01mnot[39;00m file_like[38;5;241m.[39mendswith([38;5;124m'[39m[38;5;124m.mat[39m[38;5;124m'[39m):
[1;32m     44[0m         file_like [38;5;241m+[39m[38;5;241m=[39m [38;5;124m'[39m[38;5;124m.mat[39m[38;5;124m'[39m
[0;32m---> 45[0m     [38;5;28;01mreturn[39;00m [38;5;28;43mopen[39;49m[43m([49m[43mfile_like[49m[43m,[49m[43m [49m[43mmode[49m[43m)[49m, [38;5;28;01mTrue[39;00m
[1;32m     46[0m [38;5;28;01melse[39;00m:
[1;32m     47[0m     [38;5;28;01mraise[39;00m [38;5;167;01mOSError[39;00m(
[1;32m     48[0m         [38;5;124m'[39m[38;5;124mReader needs file name or open file-like object[39m[38;5;124m'[39m
[1;32m     49[0m     ) [38;5;28;01mfrom[39;00m[38;5;250m [39m[38;5;21;01me[39;00m

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: '/Users/andreanovoa/data/annular/ER_0.4875.mat'

__________ test_notebook_runs[tutorials/25_TABADA_annular_raw.ipynb] ___________

notebook_path = 'tutorials/25_TABADA_annular_raw.ipynb'

    @pytest.mark.parametrize("notebook_path", NOTEBOOKS)
    def test_notebook_runs(notebook_path):
        """Test that a notebook runs without error."""
>       assert run_notebook(notebook_path, timeout=TIMEOUT, quick=QUICK), f"Notebook failed: {notebook_path}"
E       AssertionError: Notebook failed: tutorials/25_TABADA_annular_raw.ipynb
E       assert False
E        +  where False = run_notebook('tutorials/25_TABADA_annular_raw.ipynb', timeout=600, quick=False)

test_tutorials.py:71: AssertionError
----------------------------- Captured stdout call -----------------------------
Testing tutorials/25_TABADA_annular_raw.ipynb...Error executing tutorials/25_TABADA_annular_raw.ipynb: An error occurred while executing the following cell:
------------------
import matplotlib; matplotlib.use('Agg')  # Disable plotting
from essentials.models_physical import Annular
from essentials.create import create_truth
import os

ER = 0.4875 + 0.025 * 2 # 0.4875 + np.arange(0, 4) * 0.025

results_folder += 'ER{}/'.format(ER)
os.makedirs(results_folder, exist_ok=True)

t_start = Annular.t_transient
t_stop = t_start + Annular.t_CR * 15

truth = create_truth(model = data_folder + 'ER_{}'.format(ER),
                     t_start = t_start,
                     t_stop = t_stop,
                     Nt_obs = 35,
                     t_max = t_stop + Annular.t_transient,
                     post_processed=False
                     )

------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
File [0;32m~/anaconda3/envs/sort/lib/python3.9/site-packages/scipy/io/matlab/_mio.py:39[0m, in [0;36m_open_file[0;34m(file_like, appendmat, mode)[0m
[1;32m     38[0m [38;5;28;01mtry[39;00m:
[0;32m---> 39[0m     [38;5;28;01mreturn[39;00m [38;5;28;43mopen[39;49m[43m([49m[43mfile_like[49m[43m,[49m[43m [49m[43mmode[49m[43m)[49m, [38;5;28;01mTrue[39;00m
[1;32m     40[0m [38;5;28;01mexcept[39;00m [38;5;167;01mOSError[39;00m [38;5;28;01mas[39;00m e:
[1;32m     41[0m     [38;5;66;03m# Probably "not found"[39;00m

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: '/Users/andreanovoa/data/annular/ER_0.5375.mat'

During handling of the above exception, another exception occurred:

[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
File [0;32m~/real-time-bias-aware-DA/PRIVATE_real-time-bias-aware-DA/real_public/tutorials/../essentials/create.py:125[0m, in [0;36mcreate_observations_from_file[0;34m(name, t_max, t_min)[0m
[1;32m    124[0m     name [38;5;241m+[39m[38;5;241m=[39m [38;5;124m'[39m[38;5;124m.mat[39m[38;5;124m'[39m
[0;32m--> 125[0m mat [38;5;241m=[39m [43mload_from_mat_file[49m[43m([49m[43mname[49m[43m)[49m
[1;32m    126[0m y_raw, y_true, t_true [38;5;241m=[39m [mat[key] [38;5;28;01mfor[39;00m key [38;5;129;01min[39;00m [[38;5;124m'[39m[38;5;124my_raw[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124my_filtered[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mt[39m[38;5;124m'[39m]]

File [0;32m~/real-time-bias-aware-DA/PRIVATE_real-time-bias-aware-DA/real_public/tutorials/../essentials/Util.py:285[0m, in [0;36mload_from_mat_file[0;34m(filename, squeeze_me)[0m
[1;32m    284[0m [38;5;28;01mdef[39;00m[38;5;250m [39m[38;5;21mload_from_mat_file[39m(filename, squeeze_me[38;5;241m=[39m[38;5;28;01mTrue[39;00m):
[0;32m--> 285[0m     [38;5;28;01mreturn[39;00m [43msio[49m[38;5;241;43m.[39;49m[43mloadmat[49m[43m([49m[43mfilename[49m[43m,[49m[43m [49m[43mappendmat[49m[38;5;241;43m=[39;49m[38;5;28;43;01mTrue[39;49;00m[43m,[49m[43m [49m[43msqueeze_me[49m[38;5;241;43m=[39;49m[43msqueeze_me[49m[43m)[49m

File [0;32m~/anaconda3/envs/sort/lib/python3.9/site-packages/scipy/io/matlab/_mio.py:225[0m, in [0;36mloadmat[0;34m(file_name, mdict, appendmat, **kwargs)[0m
[1;32m    224[0m variable_names [38;5;241m=[39m kwargs[38;5;241m.[39mpop([38;5;124m'[39m[38;5;124mvariable_names[39m[38;5;124m'[39m, [38;5;28;01mNone[39;00m)
[0;32m--> 225[0m [38;5;28;01mwith[39;00m _open_file_context(file_name, appendmat) [38;5;28;01mas[39;00m f:
[1;32m    226[0m     MR, _ [38;5;241m=[39m mat_reader_factory(f, [38;5;241m*[39m[38;5;241m*[39mkwargs)

File [0;32m~/anaconda3/envs/sort/lib/python3.9/contextlib.py:119[0m, in [0;36m_GeneratorContextManager.__enter__[0;34m(self)[0m
[1;32m    118[0m [38;5;28;01mtry[39;00m:
[0;32m--> 119[0m     [38;5;28;01mreturn[39;00m [38;5;28;43mnext[39;49m[43m([49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mgen[49m[43m)[49m
[1;32m    120[0m [38;5;28;01mexcept[39;00m [38;5;167;01mStopIteration[39;00m:

File [0;32m~/anaconda3/envs/sort/lib/python3.9/site-packages/scipy/io/matlab/_mio.py:17[0m, in [0;36m_open_file_context[0;34m(file_like, appendmat, mode)[0m
[1;32m     15[0m [38;5;129m@contextmanager[39m
[1;32m     16[0m [38;5;28;01mdef[39;00m[38;5;250m [39m[38;5;21m_open_file_context[39m(file_like, appendmat, mode[38;5;241m=[39m[38;5;124m'[39m[38;5;124mrb[39m[38;5;124m'[39m):
[0;32m---> 17[0m     f, opened [38;5;241m=[39m [43m_open_file[49m[43m([49m[43mfile_like[49m[43m,[49m[43m [49m[43mappendmat[49m[43m,[49m[43m [49m[43mmode[49m[43m)[49m
[1;32m     18[0m     [38;5;28;01mtry[39;00m:

File [0;32m~/anaconda3/envs/sort/lib/python3.9/site-packages/scipy/io/matlab/_mio.py:45[0m, in [0;36m_open_file[0;34m(file_like, appendmat, mode)[0m
[1;32m     44[0m         file_like [38;5;241m+[39m[38;5;241m=[39m [38;5;124m'[39m[38;5;124m.mat[39m[38;5;124m'[39m
[0;32m---> 45[0m     [38;5;28;01mreturn[39;00m [38;5;28;43mopen[39;49m[43m([49m[43mfile_like[49m[43m,[49m[43m [49m[43mmode[49m[43m)[49m, [38;5;28;01mTrue[39;00m
[1;32m     46[0m [38;5;28;01melse[39;00m:

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: '/Users/andreanovoa/data/annular/ER_0.5375.mat'

During handling of the above exception, another exception occurred:

[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
Cell [0;32mIn[2], line 14[0m
[1;32m     11[0m t_start [38;5;241m=[39m Annular[38;5;241m.[39mt_transient
[1;32m     12[0m t_stop [38;5;241m=[39m t_start [38;5;241m+[39m Annular[38;5;241m.[39mt_CR [38;5;241m*[39m [38;5;241m15[39m
[0;32m---> 14[0m truth [38;5;241m=[39m [43mcreate_truth[49m[43m([49m[43mmodel[49m[43m [49m[38;5;241;43m=[39;49m[43m [49m[43mdata_folder[49m[43m [49m[38;5;241;43m+[39;49m[43m [49m[38;5;124;43m'[39;49m[38;5;124;43mER_[39;49m[38;5;132;43;01m{}[39;49;00m[38;5;124;43m'[39;49m[38;5;241;43m.[39;49m[43mformat[49m[43m([49m[43mER[49m[43m)[49m[43m,[49m
[1;32m     15[0m [43m                     [49m[43mt_start[49m[43m [49m[38;5;241;43m=[39;49m[43m [49m[43mt_start[49m[43m,[49m
[1;32m     16[0m [43m                     [49m[43mt_stop[49m[43m [49m[38;5;241;43m=[39;49m[43m [49m[43mt_stop[49m[43m,[49m
[1;32m     17[0m [43m                     [49m[43mNt_obs[49m[43m [49m[38;5;241;43m=[39;49m[43m [49m[38;5;241;43m35[39;49m[43m,[49m
[1;32m     18[0m [43m                     [49m[43mt_max[49m[43m [49m[38;5;241;43m=[39;49m[43m [49m[43mt_stop[49m[43m [49m[38;5;241;43m+[39;49m[43m [49m[43mAnnular[49m[38;5;241;43m.[39;49m[43mt_transient[49m[43m,[49m
[1;32m     19[0m [43m                     [49m[43mpost_processed[49m[38;5;241;43m=[39;49m[38;5;28;43;01mFalse[39;49;00m
[1;32m     20[0m [43m                     [49m[43m)[49m

File [0;32m~/real-time-bias-aware-DA/PRIVATE_real-time-bias-aware-DA/real_public/tutorials/../essentials/create.py:59[0m, in [0;36mcreate_truth[0;34m(model, t_start, t_stop, Nt_obs, std_obs, t_max, t_min, noise_type, post_processed, manual_bias, **kwargs)[0m
[1;32m     56[0m     t_max [38;5;241m=[39m t_stop [38;5;241m+[39m t_start
[1;32m     58[0m [38;5;28;01mif[39;00m [38;5;28mtype[39m(model) [38;5;129;01mis[39;00m [38;5;28mstr[39m:
[0;32m---> 59[0m     y_raw, y_true, t_true, name_truth [38;5;241m=[39m [43mcreate_observations_from_file[49m[43m([49m[43mmodel[49m[43m,[49m[43m [49m[43mt_max[49m[38;5;241;43m=[39;49m[43mt_max[49m[43m,[49m[43m [49m[43mt_min[49m[38;5;241;43m=[39;49m[43mt_min[49m[43m,[49m[43m [49m[43m)[49m
[1;32m     60[0m     case_name [38;5;241m=[39m model[38;5;241m.[39msplit([38;5;124m'[39m[38;5;124m/[39m[38;5;124m'[39m)[[38;5;241m-[39m[38;5;241m1[39m]
[1;32m     61[0m     name_bias [38;5;241m=[39m [38;5;124m'[39m[38;5;124mExp_[39m[38;5;124m'[39m [38;5;241m+[39m case_name

File [0;32m~/real-time-bias-aware-DA/PRIVATE_real-time-bias-aware-DA/real_public/tutorials/../essentials/create.py:130[0m, in [0;36mcreate_observations_from_file[0;34m(name, t_max, t_min)[0m
[1;32m    128[0m         [38;5;28;01mraise[39;00m [38;5;167;01mFileNotFoundError[39;00m
[1;32m    129[0m [38;5;28;01mexcept[39;00m [38;5;167;01mFileNotFoundError[39;00m:
[0;32m--> 130[0m     [38;5;28;01mraise[39;00m [38;5;167;01mFileNotFoundError[39;00m([38;5;124m'[39m[38;5;124mFile [39m[38;5;124m'[39m [38;5;241m+[39m name [38;5;241m+[39m [38;5;124m'[39m[38;5;124m not defined[39m[38;5;124m'[39m)
[1;32m    132[0m [38;5;28;01mif[39;00m [38;5;28mlen[39m(np[38;5;241m.[39mshape(t_true)) [38;5;241m>[39m [38;5;241m1[39m:
[1;32m    133[0m     t_true [38;5;241m=[39m np[38;5;241m.[39msqueeze(t_true)

[0;31mFileNotFoundError[0m: File /Users/andreanovoa/data/annular/ER_0.5375.mat not defined

___________ test_notebook_runs[tutorials/30_ESN-POD_cylinder.ipynb] ____________

notebook_path = 'tutorials/30_ESN-POD_cylinder.ipynb'

    @pytest.mark.parametrize("notebook_path", NOTEBOOKS)
    def test_notebook_runs(notebook_path):
        """Test that a notebook runs without error."""
>       assert run_notebook(notebook_path, timeout=TIMEOUT, quick=QUICK), f"Notebook failed: {notebook_path}"
E       AssertionError: Notebook failed: tutorials/30_ESN-POD_cylinder.ipynb
E       assert False
E        +  where False = run_notebook('tutorials/30_ESN-POD_cylinder.ipynb', timeout=600, quick=False)

test_tutorials.py:71: AssertionError
----------------------------- Captured stdout call -----------------------------
Testing tutorials/30_ESN-POD_cylinder.ipynb...Error executing tutorials/30_ESN-POD_cylinder.ipynb: An error occurred while executing the following cell:
------------------
import matplotlib; matplotlib.use('Agg')  # Disable plotting

ensemble = create_ensemble(model=case_ESN,
                           m=10,
                          std_psi=.5,
                          est_a=['Wout'],
                          std_a=0.2)


from essentials.plotResults import plot_ensemble

plot_ensemble(ensemble, max_modes=10)

------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mValueError[0m                                Traceback (most recent call last)
Cell [0;32mIn[13], line 3[0m
[1;32m      1[0m [38;5;28;01mimport[39;00m[38;5;250m [39m[38;5;21;01mmatplotlib[39;00m; matplotlib[38;5;241m.[39muse([38;5;124m'[39m[38;5;124mAgg[39m[38;5;124m'[39m)  [38;5;66;03m# Disable plotting[39;00m
[0;32m----> 3[0m ensemble [38;5;241m=[39m [43mcreate_ensemble[49m[43m([49m[43mmodel[49m[38;5;241;43m=[39;49m[43mcase_ESN[49m[43m,[49m
[1;32m      4[0m [43m                           [49m[43mm[49m[38;5;241;43m=[39;49m[38;5;241;43m10[39;49m[43m,[49m
[1;32m      5[0m [43m                          [49m[43mstd_psi[49m[38;5;241;43m=[39;49m[38;5;241;43m.5[39;49m[43m,[49m
[1;32m      6[0m [43m                          [49m[43mest_a[49m[38;5;241;43m=[39;49m[43m[[49m[38;5;124;43m'[39;49m[38;5;124;43mWout[39;49m[38;5;124;43m'[39;49m[43m][49m[43m,[49m
[1;32m      7[0m [43m                          [49m[43mstd_a[49m[38;5;241;43m=[39;49m[38;5;241;43m0.2[39;49m[43m)[49m
[1;32m     10[0m [38;5;28;01mfrom[39;00m[38;5;250m [39m[38;5;21;01messentials[39;00m[38;5;21;01m.[39;00m[38;5;21;01mplotResults[39;00m[38;5;250m [39m[38;5;28;01mimport[39;00m plot_ensemble
[1;32m     12[0m plot_ensemble(ensemble, max_modes[38;5;241m=[39m[38;5;241m10[39m)

File [0;32m~/real-time-bias-aware-DA/PRIVATE_real-time-bias-aware-DA/real_public/tutorials/../essentials/create.py:41[0m, in [0;36mcreate_ensemble[0;34m(model, forecast_params, dt, alpha0, **filter_params)[0m
[1;32m     38[0m ensemble[38;5;241m.[39mupdate_history(state[[38;5;241m-[39m[38;5;241m1[39m], reset[38;5;241m=[39m[38;5;28;01mTrue[39;00m)
[1;32m     40[0m [38;5;66;03m# =========================  INITIALISE ENSEMBLE & BIAS  =========================== #[39;00m
[0;32m---> 41[0m [43mensemble[49m[38;5;241;43m.[39;49m[43minit_ensemble[49m[43m([49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mfilter_params[49m[43m)[49m
[1;32m     43[0m ensemble[38;5;241m.[39mclose()
[1;32m     44[0m [38;5;28;01mreturn[39;00m ensemble

File [0;32m~/real-time-bias-aware-DA/PRIVATE_real-time-bias-aware-DA/real_public/tutorials/../essentials/model.py:276[0m, in [0;36mModel.init_ensemble[0;34m(self, seed, ensemble_psi0, **kwargs)[0m
[1;32m    274[0m [38;5;28;01mif[39;00m [38;5;28mself[39m[38;5;241m.[39mest_a:  [38;5;66;03m# Augment ensemble with estimated input_parameters: psi = [psi; alpha][39;00m
[1;32m    275[0m     mean_a [38;5;241m=[39m np[38;5;241m.[39marray([[38;5;28mgetattr[39m([38;5;28mself[39m, pp) [38;5;28;01mfor[39;00m pp [38;5;129;01min[39;00m [38;5;28mself[39m[38;5;241m.[39mest_a])
[0;32m--> 276[0m     new_alpha0 [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43madd_uncertainty[49m[43m([49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mrng[49m[43m,[49m[43m [49m[43mmean_a[49m[43m,[49m[43m [49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mstd_a[49m[43m,[49m[43m [49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mm[49m[43m,[49m
[1;32m    277[0m [43m                                      [49m[43mmethod[49m[38;5;241;43m=[39;49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43malpha_distr[49m[43m,[49m[43m [49m[43mensure_mean[49m[38;5;241;43m=[39;49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mensure_mean[49m[43m)[49m
[1;32m    278[0m     ensemble_psi0 [38;5;241m=[39m np[38;5;241m.[39mvstack((ensemble_psi0, new_alpha0))
[1;32m    279[0m [38;5;28;01melse[39;00m:

File [0;32m~/real-time-bias-aware-DA/PRIVATE_real-time-bias-aware-DA/real_public/tutorials/../essentials/model.py:233[0m, in [0;36mModel.add_uncertainty[0;34m(rng, mean, std, m, method, ensure_mean)[0m
[1;32m    231[0m [38;5;28;01melif[39;00m [38;5;28mtype[39m(std) [38;5;129;01mis[39;00m [38;5;28mfloat[39m:
[1;32m    232[0m     [38;5;28;01mif[39;00m method [38;5;241m==[39m [38;5;124m'[39m[38;5;124muniform[39m[38;5;124m'[39m:
[0;32m--> 233[0m         ensemble_ [38;5;241m=[39m np[38;5;241m.[39marray([ma [38;5;241m*[39m ([38;5;241m1.[39m [38;5;241m+[39m rng[38;5;241m.[39muniform([38;5;241m-[39mstd, std, m)) [38;5;28;01mfor[39;00m ma [38;5;129;01min[39;00m mean])
[1;32m    234[0m     [38;5;28;01melse[39;00m:
[1;32m    235[0m         ensemble_ [38;5;241m=[39m rng[38;5;241m.[39mmultivariate_normal(mean, np[38;5;241m.[39mdiag((mean [38;5;241m*[39m std) [38;5;241m*[39m[38;5;241m*[39m [38;5;241m2[39m), m)[38;5;241m.[39mT

File [0;32m~/real-time-bias-aware-DA/PRIVATE_real-time-bias-aware-DA/real_public/tutorials/../essentials/model.py:233[0m, in [0;36m<listcomp>[0;34m(.0)[0m
[1;32m    231[0m [38;5;28;01melif[39;00m [38;5;28mtype[39m(std) [38;5;129;01mis[39;00m [38;5;28mfloat[39m:
[1;32m    232[0m     [38;5;28;01mif[39;00m method [38;5;241m==[39m [38;5;124m'[39m[38;5;124muniform[39m[38;5;124m'[39m:
[0;32m--> 233[0m         ensemble_ [38;5;241m=[39m np[38;5;241m.[39marray([[43mma[49m[43m [49m[38;5;241;43m*[39;49m[43m [49m[43m([49m[38;5;241;43m1.[39;49m[43m [49m[38;5;241;43m+[39;49m[43m [49m[43mrng[49m[38;5;241;43m.[39;49m[43muniform[49m[43m([49m[38;5;241;43m-[39;49m[43mstd[49m[43m,[49m[43m [49m[43mstd[49m[43m,[49m[43m [49m[43mm[49m[43m)[49m[43m)[49m [38;5;28;01mfor[39;00m ma [38;5;129;01min[39;00m mean])
[1;32m    234[0m     [38;5;28;01melse[39;00m:
[1;32m    235[0m         ensemble_ [38;5;241m=[39m rng[38;5;241m.[39mmultivariate_normal(mean, np[38;5;241m.[39mdiag((mean [38;5;241m*[39m std) [38;5;241m*[39m[38;5;241m*[39m [38;5;241m2[39m), m)[38;5;241m.[39mT

[0;31mValueError[0m: operands could not be broadcast together with shapes (51,4) (10,) 

=============================== warnings summary ===============================
../../../anaconda3/envs/sort/lib/python3.9/site-packages/jupyter_client/connect.py:22
  /Users/andreanovoa/anaconda3/envs/sort/lib/python3.9/site-packages/jupyter_client/connect.py:22: DeprecationWarning: Jupyter is migrating its paths to use standard platformdirs
  given by the platformdirs library.  To remove this warning and
  see the appropriate new directories, set the environment variable
  `JUPYTER_PLATFORM_DIRS=1` and then run `jupyter --paths`.
  The use of platformdirs will be the default in `jupyter_core` v6
    from jupyter_core.paths import jupyter_data_dir, jupyter_runtime_dir, secure_write

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== short test summary info ============================
FAILED test_tutorials.py::test_notebook_runs[tutorials/20_Rijke_LOM.ipynb] - ...
FAILED test_tutorials.py::test_notebook_runs[tutorials/21_TADA_Rijke_twin.ipynb]
FAILED test_tutorials.py::test_notebook_runs[tutorials/24_TA_azimuthal_data.ipynb]
FAILED test_tutorials.py::test_notebook_runs[tutorials/25_TABADA_annular_raw.ipynb]
FAILED test_tutorials.py::test_notebook_runs[tutorials/30_ESN-POD_cylinder.ipynb]
============= 5 failed, 11 passed, 1 warning in 144.26s (0:02:24) ==============
